### ISSUE TITLE
Can't be used with System.Text.Json source generation

### ISSUE THREAD

**Issue by distantcam** [KristofferStrube/ActivityStreams#4]
While working on a project using ActivityStreams I thought I'd try using the new System.Text.Json source generation.

Unfortunately there's an issue because the converter types are internal.

```csharp
[JsonSerializable(typeof(Person))]
public partial class ActivityStreamJsonSerializerContext : JsonSerializerContext {}
```

Produces the following compiler errors.

> error CS0122: 'LinkConverter' is inaccessible due to its protection level
> error CS0122: 'EndpointsOrLinkConverter' is inaccessible due to its protection level
> error CS0122: 'ObjectOrLinkConverter' is inaccessible due to its protection level
> error CS0122: 'ImageOrLinkConverter' is inaccessible due to its protection level
> error CS0122: 'CollectionPageOrLinkConverter' is inaccessible due to its protection level
> error CS0122: 'TermDefinitionConverter' is inaccessible due to its protection level
> error CS0122: 'XMLTimeSpanConverter' is inaccessible due to its protection level

Could the converters please be changed to public?

**Comment by KristofferStrube** [comment]
The change should be available in [version 0.2.1](https://www.nuget.org/packages/KristofferStrube.ActivityStreams/0.2.1).

Please don't hesitate to reach out if you have any other problems. 😊
